version: '3'
services:
  postgres:
    image: postgres:12.6
    volumes:
      - ./postgresdb:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user-pwd
      POSTGRES_DB: todo

volumes:
  postgresdb:
    driver: local